### ISSUE TITLE
Lua error with v13

### ISSUE THREAD

**Issue by lowpita** [kemayo/wow-handynotes-dragonflight#1]
Hey. As of today's v13 release I'm getting the following error when loading or reloading into the game while only having bugsack, buggrabber, handynotes and handynotes dragonflight enabled: 

33x ...tes_DragonflightTreasures/handler/routes_minimap.lua:27: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@HandyNotes_DragonflightTreasures/handler/routes_minimap.lua"]:27: in function `RefreshAllData'
[string "@HandyNotes_DragonflightTreasures/handler/routes_minimap.lua"]:194: in function `UpdateMinimapRoutes'
[string "@HandyNotes_DragonflightTreasures/handler/routes_minimap.lua"]:75: in function <...tes_DragonflightTreasures/handler/routes_minimap.lua:73>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by kemayo** [comment]
Oops, this is what I get for only testing that while sitting in the dragonflight beta zones. Thanks!
