### ISSUE TITLE
More profession items quest IDs

### ISSUE THREAD

**Issue by tfmonk** [kemayo/wow-handynotes-dragonflight#10]
# Tailoring
### Thaldraszus

[Miniature Bronze Dragonflight Banner](https://www.wowhead.com/item=198684/miniature-bronze-dragonflight-banner)  60.40 79.70
[60407970] = {quest=70288, label=""},

[Ancient Dragonweave Bolt](https://www.wowhead.com/item=201019/ancient-dragonweave-bolt) 58.68 45.87
[58684587] = {quest=70372, label=""},

### Azure Span
[Intriguing bolt of blue cloth](https://www.wowhead.com/item=198662/intriguing-bolt-of-blue-cloth) 40.68 54.93
[40685493] = {quest=70267, label=""},

[Decaying Brackenhide Blanket](https://www.wowhead.com/item=198680/decaying-brackenhide-blanket) 16.18 38.92
[16183892] = {quest=70284, label=""},

### Ohn'ahran Plains
[Silky Surprise](https://www.wowhead.com/item=201020/silky-surprise) 65.93 53.27
[65935327] = {quest=70303, label=""},

[Noteworthy Scrap of Carpet](https://www.wowhead.com/item=198692/noteworthy-scrap-of-carpet) 35.37 40.16 
 _*The icon on the map is in the wrong plan as well*_
[35374016] = {quest=70295, label=""},

### The Waking Shore
[Itinerant Singed Fabric](https://www.wowhead.com/item=198702/itinerant-singed-fabric) 25.13 69.77
[25136977] = {quest=70304, label=""},

[Mysterious Banner](https://www.wowhead.com/item=198699/mysterious-banner) 74.77 37.97
[74773797] = {quest=70302, label=""},

# Enchanting
### Azure Span
[Forgotton arcane tome](https://www.wowhead.com/object=380647/forgotton-arcane-tome) 38.50 59.11
[38505911] = {quest=70336, label=""},

[Faintly Enchanted Remains](https://www.wowhead.com/item=201013/faintly-enchanted-remains) 45.18 61.08
[45186108] = {quest=70290, label=""},

### Thaldraszus
[Fractured Titanic Sphere](https://www.wowhead.com/item=198800/fractured-titanic-sphere) 59.92 70.34
[59927034] = {quest=70342, label=""},

**Comment by tfmonk** [comment]
Also you spelled my name wrong on your change log :)

**Comment by kemayo** [comment]
...huh, so I did. Well, I'll fix that. 😆

**Comment by tfmonk** [comment]
@kemayo Noteworthy Scrap of Carpet in Ohn'ahran Plains hasnt been updated

**Comment by kemayo** [comment]
Okay, that's properly added in now. 🥇
