### ISSUE TITLE
[Honor our Ancestors] quality does not matter

### ISSUE THREAD

**Issue by Mr-nUUb** [kemayo/wow-handynotes-dragonflight#13]
[Muqur Swiftshot](https://www.wowhead.com/npc=197050) wants boots enchantments. This addon states highest quality, but in fact lowest quality suffices.

This addon: [Enchant Boots - Plainsrunner's Breeze](https://www.wowhead.com/item=200018)
What I turned in: [Enchant Boots - Plainsrunner's Breeze](https://www.wowhead.com/item=199934)

**Comment by kemayo** [comment]
Thanks, I'll update the requirements!
