### ISSUE TITLE
Enchanting Prof Treasure

### ISSUE THREAD

**Issue by tfmonk** [kemayo/wow-handynotes-dragonflight#14]
# Enchanting
### The waking shore
[Flashfrozen Scroll](https://www.wowhead.com/item=198798/flashfrozen-scroll) 57.50 83.59
[57508359] = {quest=70320, label=""},

**Comment by kemayo** [comment]
Nice, thanks!

**Comment by kemayo** [comment]
This was added in 044759e476c6184a84e19862f94998e179cb5187, I just forgot to close the issue.
