### ISSUE TITLE
Blacksmithing Treasures

### ISSUE THREAD

**Issue by tfmonk** [kemayo/wow-handynotes-dragonflight#15]
# Blacksmithing

### The Waking Shore
[Curious Ingots](https://www.wowhead.com/item=201005/curious-ingots)
[65552571] = {quest=70312, label=""},

[Glimmer of  Blacksmithing Wisdom](https://www.wowhead.com/item=198791/glimmer-of-blacksmithing-wisdom)
[56311946] = {quest=70232, label=""}, 
[56311946] = {quest=71352, label=""}, 
_*Not 100% sure which quest id is right as both popped at the same time i think 70232 as it was the last one and reward was last item received*_

Profession Master - [Grekka Anvilsmash](https://www.wowhead.com/npc=194836/grekka-anvilsmash)
[43306666] = {quest=70250, label=""},

[Molten Ingot](https://www.wowhead.com/item=201008/molten-ingot)
[35396432] = {quest=70296, label=""},

[Qalashi Weapon Diagram](https://www.wowhead.com/item=201010/qalashi-weapon-diagram)
[34476709] = {quest=70310, label=""},

[Ancient Monument](https://www.wowhead.com/item=201007/ancient-monument)
[22278764] = {quest=70246, label=""},

### Ohn'ahran Plains
[Ancient Spear Shards](https://www.wowhead.com/item=201004/ancient-spear-shards)
[81103790] = {quest=70313, label=""},

[Falconer Gauntlet Drawings](https://www.wowhead.com/item=201009/falconer-gauntlet-drawings)
[50916657] = {quest=70353, label=""},

### The Azure Span
[Spelltouched Tongs](https://www.wowhead.com/item=201011/spelltouched-tongs)
[53126609] = {quest=70314, label=""},

### Thaldraszus
[Draconic Flux](https://www.wowhead.com/item=201006/draconic-flux)
[52248054] = {quest=70311, label=""},

**Comment by kemayo** [comment]
Nice, thanks! I've added these in 8801c6ed6de16f4b6cffa18c1cfa47628a2d884b.
