### ISSUE TITLE
[Expedition Scout's Pack] not showing

### ISSUE THREAD

**Issue by Mr-nUUb** [kemayo/wow-handynotes-dragonflight#16]
Expedition Scout's Packs do not show on Taldraszus and Azure Span. I tried disabling/enabling, resetting hidden nodes and reloading - nothing changes. They work flawlessly in Ohn'ahran Plains and Waking Shores.
![grafik](https://user-images.githubusercontent.com/36689675/206796718-07bac65f-fc2a-4c27-96f4-77a58c7f935e.png)

**Comment by Mr-nUUb** [comment]
I somehow fixed it by enabling them in submenu "Zone/Talraszus" and "Zone/The Azure Span". I have no idea what's going on :shrug:

**Comment by kemayo** [comment]
It's separately disabled per-zone for you in those zones -- note that "currently hidden in this zone" bit in the tooltip -- which you can change in the `zone` submenu.

I should maybe have the top-level checkbox reset/override the current zone setting if it exists, such that toggling it removes that override.

**Comment by Mr-nUUb** [comment]
I think a hint in the tooltip where to change this override would be good. Thanks for clarifying this.
