### ISSUE TITLE
Missing Profession Knowledge/Master Quest IDs

### ISSUE THREAD

**Issue by crusha015** [kemayo/wow-handynotes-dragonflight#20]
Alchemy:
- Frostforged Potion - 70274
- Well Insulated Mug -70289
- Canteen of Suspicious Water -70305
- Experimental Decay Sample - 70208
- Firewater Powder Sample - 70309
- Furry Gloop - 70278
- Contraband Concoction - 70301

Enchanting:
- Enriched Earthen Shard - 70298

Jewelcrafting:
- Crystalline Overgrowth - 70277
- Harmonic Crystal Harmonizer - 70271

Leatherworking:
- Poacher's Pack - 70308
- Decay-Infused Tanning Oil - 70266

Masters:
- Skinning - 70259
- Alchemy - 70247
- Jewelcrafting - 70255

**Comment by kemayo** [comment]
Nice, thank you! I'll get those added.
