### ISSUE TITLE
The Map Marker for the Teerkai Ancestor related to the "Honor Our Ancestors" achievement shows the wrong required item

### ISSUE THREAD

**Issue by Ghostopheles** [kemayo/wow-handynotes-dragonflight#21]
The icon and tooltip for the Teerkai Ancestor (npc id: 197057) at 41.54, 56.73 in the Ohn'aran Plains zone shows the ghost as requiring a Primal Molten Greatbelt instead of the newly required Fire-Blessed Greatsword (id: 199049).

During the Beta (and maybe even early after launch) it required the Greatbelt, but has since been changed to the Fire-Blessed Greatsword. The stats/version of the Fire-Blessed Greatsword don't seem to matter for the turn-in.

**Comment by kemayo** [comment]
Huh, thanks, I hadn't noticed that change. Seems much better, really.
