### ISSUE TITLE
Treasure Bug

### ISSUE THREAD

**Issue by Pyzam** [kemayo/wow-handynotes-dragonflight#25]
![Bug proof](https://user-images.githubusercontent.com/70659484/211206533-0a891341-b0a8-43b5-9b6e-f021bd5c530b.jpg)

ADDON VERSION: v41

Describe the bug
The addon shows 2 Emerald Gardens Explorer's Notes, when 1 of them is supposed to display "Ruby Gem Cluster"

Here are the ID's Ruby Gem Cluster is associated with.

Quest flagged when used: 70528

Quest flagged when looted: 70598

**Comment by kemayo** [comment]
Thanks for pointing this one out!

**Comment by kemayo** [comment]
I failed to actually note this in the commit, so: aee4875a4708b28513c2f47a1263567c0c2cdbf3
