### ISSUE TITLE
Missing rare: Zerimek

### ISSUE THREAD

**Issue by KyrosKrane** [kemayo/wow-handynotes-dragonflight#29]
https://www.wowhead.com/npc=188451/zerimek

Spawns in Oh'naran Plains, map ID 2023 at 72.2, 23.1. Only spawns when the Aaylaag camp is at its north spot.

Doesn't appear to have any noteworthy loot, but he is a criterion for the "Adventurer of the Ohn'ahran Plains" achievement.

**Comment by kemayo** [comment]
Zerimek is already in there: https://github.com/kemayo/wow-handynotes-dragonflight/blob/2148638e84df9786ff52ae3426d7bab827633a1f/zones/OhnahranPlains.lua#L559
