### ISSUE TITLE
GetUnit error

### ISSUE THREAD

**Issue by Ravager1240** [kemayo/wow-handynotes-dragonflight#3]
Getr this error when mousing over the main map icons. Already notified NPC time as well..

Message: Interface/AddOns/NPCTime/NPCTime.lua:24: attempt to call method 'GetUnit' (a nil value)
Time: Wed Nov 30 21:03:52 2022
Count: 1
Stack: Interface/AddOns/NPCTime/NPCTime.lua:24: attempt to call method 'GetUnit' (a nil value)
[string "@Interface/AddOns/NPCTime/NPCTime.lua"]:24: in function `ShowTime'
[string "@Interface/AddOns/NPCTime/NPCTime.lua"]:60: in function <Interface/AddOns/NPCTime/NPCTime.lua:59>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HandyNotes_DragonflightTreasures/handler/handler.lua"]:931: in function <...HandyNotes_DragonflightTreasures/handler/handler.lua:766>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/HandyNotes_DragonflightTreasures/handler/handler.lua"]:1004: in function <...HandyNotes_DragonflightTreasures/handler/handler.lua:980>
[string "=[C]"]: ?
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:56: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:51>
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:166: in function `OnEnter'
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:399: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:398>

Locals: self = Frame {
 0 = <userdata>
 Help = <function> defined @Interface/AddOns/NPCTime/NPCTime.lua:76
 OnLoad = <function> defined @Interface/AddOns/NPCTime/NPCTime.lua:56
 ShowTime = <function> defined @Interface/AddOns/NPCTime/NPCTime.lua:22
 OnEvent = <function> defined @Interface/AddOns/NPCTime/NPCTime.lua:15
}
self = HandyNotes_DragonflightTreasuresComparisonTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetExistingSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootItem = <function> defined @Interfac

**Comment by kemayo** [comment]
This one is NPCtime's issue -- it has improperly updated for the tooltip changes in 10.0.2. The changes make it so that by default your tooltip handlers run on _every_ tooltip, not just GameTooltip -- but only GameTooltip has the `GetItem`/`GetUnit` methods now.

It needs to either filter its handler to make sure it's only modifying GameTooltip (`if tooltip ~= GameTooltip then return end`), or it needs to replace its call to `tooltip:GetUnit()` with `TooltipUtil.GetDisplayedItem(tooltip)`.
