### ISSUE TITLE
 attempt to index field 'conditions' (a nil value)

### ISSUE THREAD

**Issue by milotic** [kemayo/wow-handynotes-dragonflight#37]
Date: 2024-06-03 22:25:54
ID: 1
Error occured in: Global
Count: 1
Message: ...ns/HandyNotes_DragonflightTreasures/dragonflight.lua line 23:
   attempt to index field 'conditions' (a nil value)
Debug:
   [string "@Interface/AddOns/HandyNotes_DragonflightTreasures/dragonflight.lua"]:23: in main chunk
Locals:
myname = "HandyNotes_DragonflightTreasures"
ns = <table> {
 FACTION_DREAMWARDENS = 2574
 FACTION_LOAMM = 2564
 ZARALEKCAVERN = 2133
 VALDRAKKEN = 2112
 FORBIDDENREACHINTRO = 2118
 FACTION_ISKAARA = 2511
 AZURESPAN = 2024
 FACTION_MARUUK = 2503
 THALDRASZUS = 2025
 FACTION_VALDRAKKEN = 2510
 FACTION_DRAGONSCALE = 2507
 PRIMALISTFUTURE = 2085
 WAKINGSHORES = 2022
 FORBIDDENREACH = 2151
 EMERALDDREAM = 2200
 OHNAHRANPLAINS = 2023
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'conditions' (a nil value)"

AddOns:
  Swatter, v<%version%> (<%codename%>)
  WowheadLooter, v100207
  Ace3, vr1342
  AddonFactory, v10.2.016
  AllTheThings, vDF-3.12.5
  Altoholic, v10.2.016
  Atlas, vv1.52.08
  AtlasArena, vv1.07.09
  AtlasBattleforAzeroth, vv1.52.04
  AtlasBattlegrounds, vv1.52.03
  AtlasBurningCrusade, vv1.52.03
  AtlasCataclysm, vv1.52.03
  AtlasClassicWoW, vv1.52.05
  AtlasClassOrderHalls, vv1.52.04
  AtlasDungeonLocs, vv1.52.04
  AtlasLegion, vv1.52.04
  AtlasMistsofPandaria, vv1.52.04
  AtlasOutdoorRaids, vv1.52.04
  AtlasTransportation, vv1.52.04
  AtlasWarlordsofDraenor, vv1.52.03
  AtlasWorldEvents, vv3.33
  AtlasWrathoftheLichKing, vv1.52.03
  AtlasLoot, vv8.13.14
  Auctioneer, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.15 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.15 (OneMawTime)
  AutoRepair, v
  BattlePetDailyTamer, v3.2.13
  BeStride, v2.0.20
  BigWigs, vv333
  CanIMogIt, v10.2.7v1.55
  Capping, vv10.2.8
  DataStore, v2024.06.02
  DataStoreAchievements, v2024.05.24
  DataStoreAgenda, v2024.05.20
  DataStoreAuctions, v2024.05.24
  DataStoreCharacters, v2024.05.20
  DataStoreContainers, v2024.05.20
  DataStoreCrafts, v2024.05.20
  DataStoreCurrencies, v2024.05.20
  DataStoreGarrisons, v2024.05.20
  DataStoreInventory, v2024.05.24
  DataStoreMails, v2024.05.20
  DataStorePets, v2024.05.20
  DataStoreQuests, v2024.05.20
  DataStoreReputations, v2024.05.20
  DataStoreSpells, v2024.05.20
  DataStoreStats, v2024.05.20
  DataStoreTalents, v2024.05.20
  DBMArchaeology, vr61
  DBMCore, v10.2.46-10-ge4694f7
  DBMSoundEventsPack, v1.6.35
  DBMStatusBarTimers, v10.2.46-10-ge4694f7
  DBMVPVEM, v4a4d6f5
  FactionAddict, v1.87
  FlashTaskBar, v
  Genie, vr408
  GenieLDB, vr408
  GenieUI, vr408
  Grail, v121
  GupPet, v10.0.0
  HandyNotes, vv1.6.19
  HandyNotesArgus, vv0.39
  HandyNotesBattleForAzeroth, v18
  HandyNotesBattleForAzerothTreasures, vv31-2-ge9008f1
  HandyNotesBrokenShore, vv1.52
  HandyNotesCovenantSanctum, vv26
  HandyNotesDragonflight, v46
  HandyNotesDragonflightTreasures, vv56-2-ge98ff95
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v9.1.BETA.5.15 (OneMawTime)
  TomTom, vv3.6.2-release
  BlizRuntimeLib v10.2.7.54904(US) <esMX>
  (ck=8cc)

**Comment by kemayo** [comment]
Where did you get the copy of the addon you're running? All three issues you've filed are saying that it's missing the "handler" files.

**Comment by milotic** [comment]
wowup client 
![Captura de pantalla 2024-06-04 090553](https://github.com/kemayo/wow-handynotes-dragonflight/assets/1099848/1d77e799-21e4-4a1e-b7c8-e76b0d33ea18)

**Comment by kemayo** [comment]
...is this in the War Within beta?

**Comment by milotic** [comment]
nope, retail/remix

**Comment by milotic** [comment]
fixed
