### ISSUE TITLE
Dragonscale Expedition: The Highest Peaks

### ISSUE THREAD

**Issue by Deusdictum** [kemayo/wow-handynotes-dragonflight#4]
Dragonscale Expedition: The Highest Peaks marks on the world map don't get checked off automatically. Have to do that manually.

**Comment by kemayo** [comment]
Oh right, I forgot I needed to check those questids now we're out of beta. One second...

**Comment by kemayo** [comment]
Okay, there'll be an alpha build going up in a second which should fix this. Let me know if it doesn't seem to.
