### ISSUE TITLE
Quest ID for Profession Treasures in Waking shore

### ISSUE THREAD

**Issue by tfmonk** [kemayo/wow-handynotes-dragonflight#8]
[lava infused seed](https://www.wowhead.com/item=198675/lava-infused-seed) 
Coords: 67.96, 26.77 - waking shore
Quest ID: 70283

[Enchanted Debris](https://www.wowhead.com/item=201012/enchanted-debris)
Coords: 57.52 58.49 - waking shore
Quest ID: 70272

**Comment by kemayo** [comment]
Excellent, thank you!
