### ISSUE TITLE
Ohn'ahran Plains - Enchanting Profession Knowledge

### ISSUE THREAD

**Issue by tfmonk** [kemayo/wow-handynotes-dragonflight#9]
[Storm bound horn](https://www.wowhead.com/search?q=stormbound+horn)
Coords: 61.55 67.63 
Quest ID:70291

[Shalasar glimmerdust](https://www.wowhead.com/npc=194837/shalasar-glimmerdusk)
Coords: 62.47 18.67 
Quest ID: 70251

**Comment by kemayo** [comment]
Thanks again!
